<a href="https://colab.research.google.com/github/madhukesh048/Data-Science/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Understanding Numpy** 


# What is an array?

In [1]:
# Importing numpy as np
import numpy as np

In [2]:
# Create an array using list
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
# Create an array using 3D array
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
print(b[0])

[1 2 3 4]


# How to create basic array?

In [5]:
# Create an array by passing a list
np.array([1,2,3])

array([1, 2, 3])

In [6]:
# Create an array filled with 0's
np.zeros(2)

array([0., 0.])

In [7]:
# Create an array filled with 1's
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
# Create an empty array with 2 elements
np.empty(3)

array([0.75, 0.75, 0.  ])

In [9]:
# Create an array with range of elements
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
# Create an array that contains a range of evenly spaced intervals
# np.arange(first_number,last_number,step_size)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
# Create an array with values that are spaced linearly in a specified interval
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [12]:
# Specifying data type
x = np.ones(4,dtype = np.int64)
x

array([1, 1, 1, 1])

# Adding, removing and sorting elements

In [13]:
# Sorting array
arr = np.array([2,33,11,45,22,52,18,5,4,86,19])
np.sort(arr)

array([ 2,  4,  5, 11, 18, 19, 22, 33, 45, 52, 86])

In [14]:
# Concatenate arrays
x = np.array([1,3,6,9])
y = np.array([2,4,6,8,])
np.concatenate((x,y))

array([1, 3, 6, 9, 2, 4, 6, 8])

# How do you know shape and size of an array?

In [15]:
 array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])

In [16]:
# To find dimensions of array
array_example.ndim

3

In [17]:
# To find total number of elements
array_example.size

24

In [18]:
# To find shape of array
array_example.shape

(3, 2, 4)

# Can you reshape an array?

In [19]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [20]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [21]:
np.reshape(a, newshape=(3,2),order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

# Convert 1D to 2D array

In [22]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [23]:
# np.newaxis adds new axis
a2 = a[np.newaxis,:]
a2.shape

(1, 6)

In [24]:
# converting 1D to 2D by adding row vector
row_vector = a[np.newaxis,:]
row_vector.shape

(1, 6)

In [25]:
# converting 1D to 2D by adding column vector
col_vector = a[:,np.newaxis]
col_vector.shape

(6, 1)

In [26]:
# np.expand_dims adds new axis at any given index
b = np.expand_dims(a, axis = 1)
b.shape

(6, 1)

In [27]:
c = np.expand_dims(a, axis= 0)
c.shape

(1, 6)

# Index and slicing

In [29]:
data = np.array([1,2,3,4])
data[1]

2

In [30]:
data[0:2]

array([1, 2])

In [31]:
data[1:]

array([2, 3, 4])

In [33]:
data[-2:]

array([3, 4])

In [37]:
a = np.array([[1,2,3,4],[5,6,7,8,],[8,7,3,2],[3,4,5,9]])
# printing values less than 4
print(a[a < 4])

[1 2 3 3 2 3]


In [38]:
# printing values equal to or greater than 5
five_up = a[a >= 5]
print(five_up)

[5 6 7 8 8 7 5 9]


In [39]:
# printing values divisible by 2
divisible_by2 = a[a%2 == 0]
print(divisible_by2)

[2 4 6 8 8 2 4]


In [40]:
# printing values satisfying two different conditions using & and | operator
c = a[(a > 2) & (a < 8)]
print(c)

[3 4 5 6 7 7 3 3 4 5]


In [41]:
# returning boolean values on condtions 
d = (a > 5)
print(d)

[[False False False False]
 [False  True  True  True]
 [ True  True False False]
 [False False False  True]]


In [43]:
# creating list of coordinates using zip
list_of_coordinates = list(zip(a[0],a[1]))
for coord in list_of_coordinates:
  print(coord)

(1, 5)
(2, 6)
(3, 7)
(4, 8)


# Creating an array from existing data

In [45]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [47]:
# creating new array from section of array
array1 = a[3:6]
array1

array([4, 5, 6])

In [48]:
a1 = np.array([[1,2],
               [3,4]])
a2 = np.array([[5,6],
               [7,8]])

In [49]:
# stack them vertically using np.vstack
np.vstack((a1,a2)) 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
# stack them horzionatlly using np.hstack
np.hstack((a1,a2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])